apiVersion: v1
kind: Service
metadata:
  name: contoso-website
  namespace: {{ default "stage" .Release.Namespace }}  
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
      name: http
  selector:
    app: contoso-website
  type: ClusterIP
